load("//bazel:rules.bzl", "pme_cc_test")

pme_cc_test(
    name = "person",
    size = "small",
)

pme_cc_test(
    name = "resource",
    size = "small",
)

pme_cc_test(
    name = "location",
    size = "small",
)
